### ISSUE TITLE
Encode/decode problems

### ISSUE THREAD

**Issue by gaynetdinov** [SIfoxDevTeam/eavro#12]
Hello.

I have some problems with consuming messages from kafka which were encoded using `eavro`. 
I encode message, send it to kafka and then I'm trying to consume it using confluent's `kafka-avro-console-consumer` from http://docs.confluent.io/1.0/quickstart.html
The problem is that once message is sent, consumer dies while trying to consume the message without any errors, just with `Consumed 0 messages`. 

To investigate the issue I tried to consume message from kafka using elixir's `kafka_ex` consumer. After consuming a message I decoded it and saw that it has extra empty string at the end of the message. Then I run example from the `README` and got the following:
```
12> Msg = eavro:encode(Schema, [<<"John">>, 23, true]).
<<8,74,111,104,110,46,1>>
13> eavro:decode(Schema, Msg).
{[<<"John">>,23,true],<<>>}
```
As you can see there `<<>>` at the end of the decoded message. 

Since `kafka-avro-console-consumer` tries to validate decoded message against schema I assume that it dies because of this extra empty string. Is there a way to encode original message the way that after decoding it doesn't have this extra empty string? 

Thanks!

**Comment by vjache** [comment]
Hello,
it seems you slightly misunderstand the format of a result returned by eavro:decode. The eavro:decode accept schema and a binary buffer, and returns a tuple containing data decoded at the first element, and the rest of a buffer at the second element, i.e. {Result, Buff1} = eavro:decode(Schema, Buff0). This is the way this decoder is working: it takes a schema and a byte buffer, decodes some first bytes according to schema, and returns a decoded result and a rest of the buffer to be able to continue further. So, decoder have returned a <<>> at the second element of a tuple this just means that there is no data any more, the decoding is finished!

Nevertheless, I admit that the problem you experiencing still may be caused by bug in decoder. It may be good idea to encode the problematic message by codec used by Kafka, and to send the byte array as is just right here?

**Comment by gaynetdinov** [comment]
Hello.

First of all, thanks for the quick answer and for the great explanation! 

So I used Kafka REST Proxy http://docs.confluent.io/1.0/kafka-rest/docs/intro.html to emit a message encoded using Kafka's avro codec: 

```
# Produce a message using Avro embedded data, including the schema which will
# be registered with the schema registry and used to validate and serialize
# before storing the data in Kafka
$ curl -X POST -H "Content-Type: application/vnd.kafka.avro.v1+json" \
      --data '{"value_schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\": \"name\", \"type\": \"string\"}]}", "records": [{"value": {"name": "testUser"}}]}' \
      "http://localhost:8082/topics/avrotest"
  {"offsets":[{"partition":0,"offset":0,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":21}
```

Then I fetched it(output from elixir console):
```
KafkaEx.fetch("avrotest", 0)
[%KafkaEx.Protocol.Fetch.Response{partitions: [%{error_code: 0,
     hw_mark_offset: 1, last_offset: 0,
     message_set: [%{attributes: 0, crc: 22894542, key: nil, offset: 0,
        value: <<0, 0, 0, 0, 17, 16, 116, 101, 115, 116, 85, 115, 101, 114>>}],
     partition: 0}], topic: "avrotest"}]
```

then I extracted `:value` into variable and performed decoding:

```
iex(7)> msg = List.first(m)[:value]
<<0, 0, 0, 0, 17, 16, 116, 101, 115, 116, 85, 115, 101, 114>>
iex(8)> schema = :eavro.read_schema('schema.avsc')
{:avro_record, :User, [{"name", :string}]}
iex(9)> :eavro.decode(schema, msg)
{[""], <<0, 0, 0, 17, 16, 116, 101, 115, 116, 85, 115, 101, 114>>}
```

**Comment by gaynetdinov** [comment]
I got this. 
It's not related to `eavro` I guess(I haven't checked yet) but most probably the reason why `eavro` couldn't decode message which were sent by confluent kafka producer and why conflient kafka consumer couldn't consume message which was encoded by `eavro` is the following: there are to ways of telling to avro registry which schema should be used to decode a message. Schema id could be encoded within a message itself or schema could be specified during decoding. So when I was trying to decode message which were sent by avro producer, `eavro` couldn't decode it because first 5 bytes are reserved by schema id and I guess `eavro` isn't aware of it. And when I was trying to consume a message(which were encoded by `eavro`) using confluent kafka consumer I should have specified schema to decode message because as I understand `eavro` doesn't include schema in the encoded message. 
That's a theory, I'll try to prove it today's evening.

**Comment by gaynetdinov** [comment]
So I added 'magic byte' plus schema id as 4 bytes and avro consumer started to consume and decode messages!
```
<<0>> <> <<schema_id :: size(32)>> <> encoded_message_by_eavro
```

**Comment by vjache** [comment]
Yes ,the magic byte (0) and schema ID (4 byte integer), are actually a header which is added (if I correctly understand) by Kafka producer, and should be striped by Kafka consumer. So this header is not a part of an Avro format, it is just a trick to make it possible to deserialize Avro message later, using schema registry (Zookeeper?). Here http://stackoverflow.com/a/31206063 I've found some explanations conserning to this topic.

Hence I consider this issue closed.

**Comment by gaynetdinov** [comment]
I thought it might be useful https://github.com/SIfoxDevTeam/eavro/pull/13
