### ISSUE TITLE
hex

### ISSUE THREAD

**Issue by henry-hz** [SIfoxDevTeam/eavro#14]
Hi, let me suggest to make a build using mix for Elixir users, and register on http://hex.pm with bigdata tags.

**Comment by ates** [comment]
Hi, I've no objections, what is need for that?

**Comment by henry-hz** [comment]
only to help elixir developers to find the avro lib easily. hex.pm is becoming a main point to search for libs

**Comment by ates** [comment]
I know about hex.pm. I asked about what should I add to eavro to have it available on hex.pm?
Can you provide a pull request ?

**Comment by henry-hz** [comment]
if you use 'mix' http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html  to build an erlang app, the erlang source should be on 'src' folder, and 'mix hex' commands (see 'mix help') should help you to build and publish directly in hex.pm. For erlang compilation options, see http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Compile.Erlang.html . I would love to port your code to mix, but I am too busy for the next months.

**Comment by ates** [comment]
Ok, I will try to publish eavro on hex.pm

**Comment by henry-hz** [comment]
:+1:

**Comment by cafreeman** [comment]
Hi, any chance you've been able to figure this out? I'm working on a library that depends on this one, and I'm currently not able to publish it with `eavro` listed as a dependency since it's not on Hex :(

**Comment by ates** [comment]
Tried to do that, but faced with strange problem:

```
$ rebar3 hex publish
===> Verifying dependencies...
===> Can not publish package because the following deps are not available in hex: jsx, ranch, zlists
```

All these packages are in hex, but can't figure out what is wrong.

Do you have any idea?

**Comment by cafreeman** [comment]
@ates I think it has to do with your `rebar.lock` file. Since the dependencies are already resolved to github, it isn't even looking for them on hex. [This issue](https://github.com/hexpm/rebar3_hex/issues/51) seems to indicate that if you delete the lockfile and publish, it should (hopefully) work.

**Comment by ates** [comment]
Thanks, now it's works, but got another problem with zlists package, I will contact maintainer of this packages to resolve issue

**Comment by ates** [comment]
Done. https://hex.pm/packages/eavro
